### ISSUE TITLE
Absolute zoom behavior

### ISSUE THREAD

**Issue by auditt98** [advanced-cropper/react-advanced-cropper#10]
I was trying out absolute zoom but I'm running into a weird behaviour on different image.
The absolute zoom slider can't be dragged to the left (as shown in the picture below) even though the picture has been zoomed out all the way.
![image](https://user-images.githubusercontent.com/41824920/191637217-0207191a-f4d0-43a0-9aa6-94b9ecb9c280.png)

If you resize the stencil for just a little bit, everything goes back to normal 
![image](https://user-images.githubusercontent.com/41824920/191637334-28244257-904c-4a06-8a16-cb2821cc07db.png)

Here's a reproduceable sandbox link: https://codesandbox.io/s/react-advanced-cropper-circle-forked-tlvrlj?file=/src/index.tsx:418-475

**Comment by auditt98** [comment]
To reproduce the behavior change the image source to photo1.jpg then back to photo.jpg

**Comment by Norserium** [comment]
@auditt98, I've reproduced the bug. I'm currently working at it.

**Comment by Norserium** [comment]
@auditt98, I assume that I will fix this bugs today - tomorrow.

**Comment by Norserium** [comment]
@auditt98, fixed in `0.12.1`. [Try it](https://codesandbox.io/s/react-advanced-cropper-circle-fixed-fnbrn5?file=/src/styles.scss).
