### ISSUE TITLE
Weird stencil behaviour

### ISSUE THREAD

**Issue by auditt98** [advanced-cropper/react-advanced-cropper#11]
If you zoom in an image in rectangle mode then switch to circular stencil then the shape of the stencil would be an oval instead of being a circle

https://user-images.githubusercontent.com/41824920/191641954-d4e926b6-2e42-4a87-8840-477d0f1247bb.mp4

**Comment by Norserium** [comment]
@auditt98, what's version of `react-advanced-cropper` do you use?

**Comment by Norserium** [comment]
@auditt98, could you provide the source code of the fragment with `<Cropper/>`?

**Comment by auditt98** [comment]
@Norserium I can't provide the exact source code but here's a reproducible example https://codesandbox.io/s/react-advanced-cropper-circle-forked-mct7w7?file=/src/index.tsx

**Comment by auditt98** [comment]
https://user-images.githubusercontent.com/41824920/191707395-58fe1eea-d04a-401c-ac8a-421acaaea289.mp4

Here's the steps to reproduce

**Comment by Norserium** [comment]
@auditt98, thank you. It's even better.

**Comment by Norserium** [comment]
@auditt98, fixed in `0.12.1`. [Try it](https://codesandbox.io/s/react-advanced-cropper-circle-fixed-025omg?file=/src/index.tsx).

**Comment by auditt98** [comment]
@Norserium thank you so much for the fix. I'm closing the issue.

**Comment by Norserium** [comment]
@auditt98, you are welcome!
