### ISSUE TITLE
how to use it with filepond

### ISSUE THREAD

**Issue by violabg** [advanced-cropper/react-advanced-cropper#13]
Nice component, I would like to integrate it with filepond, any suggestions?
https://pqina.nl/filepond/docs/api/plugins/image-edit/

**Comment by Norserium** [comment]
@violabg, could you create the basic sandbox with `filepond`? I will try to find time to integrate with my cropper.

**Comment by violabg** [comment]
Thanks,
Thiis is the CodeSandbox for filepond
https://codesandbox.io/s/compassionate-ramanujan-immb8r?file=/src/App.js,
Than you need to add the image-edit plugin as per
https://pqina.nl/filepond/docs/api/plugins/image-edit/
And make it compatible with your library
https://pqina.nl/filepond/docs/api/plugins/image-edit/#integrating-other-editors

**Comment by Norserium** [comment]
@violabg, any news?

**Comment by violabg** [comment]
I did some tests, I had to change something, because I want to open the editor automatically when I choose the image.
I had some troubles with the cancel method, basically we have to add the `link.current.onclose();` on it, in order to clean the files, the problem is that it works only the first time, if you cancel or remove a file, the next time you try is not working anymore.

Here is the codesandbox
https://codesandbox.io/s/react-advanced-cropper-filepond-forked-uux7uz?file=/src/App.js

**Comment by Norserium** [comment]
@violabg, it's strange. I don't see any troubles. Could you record a video that illustrates your issue?

**Comment by Norserium** [comment]
@violabg, well, I found one issue. There is [the fixed version](https://codesandbox.io/s/react-advanced-cropper-filepond-fixed-19fkjv). Try it.

**Comment by violabg** [comment]
I saw that you change from onclose() to inclose?.(), but that the source of the problem, onclose become null after the first time, so we can't call it again and filepond can't respond on changes anymore.
to test it try to :

1. upload an image
2. either cancel crop, or remove it after the crop
3. you are back to the empty state (which is fine) 
4. now onclose is null
5. upload a new image, crop it and press done
6. you get stack we a loading state

**Comment by Norserium** [comment]
https://user-images.githubusercontent.com/9862719/197995108-8f281b27-7ab5-4190-a1bf-527f24a3c1dd.mp4

@violabg, what's wrong?

**Comment by violabg** [comment]
for me is different, but is not a constant, some time you need to repeat the steps in order to see it

**Comment by Norserium** [comment]
@violabg, could you upload a video? If you use Windows you can use the simple open source software [ScreenToGif](https://www.screentogif.com/downloads).

**Comment by violabg** [comment]
https://user-images.githubusercontent.com/3963176/198023446-734269e6-835d-4ecd-af93-690334e9ba47.mp4

**Comment by Norserium** [comment]
@violabg, I assume it somehow related to uploading the image via `api`. Do you use it?

**Comment by Norserium** [comment]
@violabg, could you to reproduce the bug [here](https://codesandbox.io/s/w6q1e?file=/src/index.js)?

**Comment by Norserium** [comment]
@violabg, I don't get why I can't reproduce that bug. Do you have any bugs with `imageEditInstantEdit={false}`?

**Comment by violabg** [comment]
> @violabg, could you to reproduce the bug [here](https://codesandbox.io/s/w6q1e?file=/src/index.js)?

no, this is working fine

**Comment by Norserium** [comment]
@violabg, could you provide the logs in the bugged case in [this example](https://codesandbox.io/s/react-advanced-cropper-filepond-fixed-19fkjv)?

**Comment by violabg** [comment]
`
[submit] [before] onclose 
undefined
[cancel] oncancel 
▶ƒ () {}
[submit] [after] onclose 
▶ƒ () {}
`

**Comment by violabg** [comment]
this is a new codesandbox

https://codesandbox.io/s/react-advanced-cropper-filepond-forked-uux7uz?file=/src/App.js

as you can see the first file is fine, if you add a second it get stack on a loading state, I think the problem is onclose fn that is null the second time, but can't figure it out why.
Maybe we should move the conversation on the filepond repository

**Comment by Norserium** [comment]
> [submit] [before] onclose undefined [cancel] oncancel ▶ƒ () {} [submit] [after] onclose ▶ƒ () {}

That's totally correct. But you have problem not on cancel, but on submit. Try to reproduce the bug, that you have illustrated on the video before.

**Comment by Norserium** [comment]
@violabg, what's browser do you use? Could you try it on device with another operating system?

**Comment by Norserium** [comment]
> @violabg, could you to reproduce the bug [here](https://codesandbox.io/s/w6q1e?file=/src/index.js)?

Hm, I've sent the wrong link. [The right one](https://codesandbox.io/s/react-filepond-image-editor-resize-demo-forked-mepwgu?file=/src/index.js).

**Comment by violabg** [comment]
> > @violabg, could you to reproduce the bug [here](https://codesandbox.io/s/w6q1e?file=/src/index.js)?
> 
> Hm, I've sent the wrong link. [The right one](https://codesandbox.io/s/react-filepond-image-editor-resize-demo-forked-mepwgu?file=/src/index.js).

is working, but you are right, is browser related, I was using safari, I tried on Chrome and is working.

**Comment by Norserium** [comment]
@violabg, well, that's something.

Try to reproduce the bug, that you have illustrated on the video before, in [this sandbox](https://codesandbox.io/s/react-advanced-cropper-filepond-fixed-19fkjv?file=/src/App.js) and send me the full console content. I assume, that somehow line after `[submit] [after] onclose` is not called.

**Comment by Norserium** [comment]
@violabg, any progress?

**Comment by Norserium** [comment]
@violabg, look, `onclose` is defined, so... it's more complicated case.

**Comment by Norserium** [comment]
@violabg, what's version of the Safari do you use?

**Comment by Norserium** [comment]
@violabg, I've tested on `14.1`, and it works well.

**Comment by violabg** [comment]
> @violabg, I've tested on `14.1` now, and it works well.

16

**Comment by Norserium** [comment]
@violabg, well, it's hard. Could you provide me the remote access via, for example, [AnyDesk](https://anydesk.com/) to debug that case (the code should be provided via email, of course, not here)?

**Comment by Norserium** [comment]
@violabg, any news?

**Comment by violabg** [comment]
Sorry i have been very busy at work these days, no progress on it.

**Comment by Norserium** [comment]
@violabg, if you find some spare time, we can debug it together. Write me a letter in this case.

**Comment by Norserium** [comment]
@violabg, any news?

**Comment by Norserium** [comment]
@violabg, I close issue. Feel free to reopen, when you return to this task.

**Comment by violabg** [comment]
It’s ok, sorry for not being available, but I have a new job and been very busy

**Comment by Norserium** [comment]
@violabg, good luck on your new job!

**Comment by yangfancn** [comment]
@Norserium ,Can provide an example for vue3? thanks!
filepond-plugin-image-edit onconfirm data is difficult to calculate, when use zoom and rotate
