### ISSUE TITLE
How to unzoom outside of image limits

### ISSUE THREAD

**Issue by koryonik** [advanced-cropper/react-advanced-cropper#14]
Hi there,
First of all, thanks for this geat component :)

I'm trying to  allow unzoom background image more than image limits. It can be useful to crop for example, a logo in horizontal format in a plain square stencil with filling areas outside the image by a default color.
Any idea to do this?

Thanks

**Comment by koryonik** [comment]
@Norserium perfect! I'll try to adapt your example for my use case :) thanks!

**Comment by Norserium** [comment]
@koryonik, any news?

**Comment by Norserium** [comment]
@koryonik, I close the issue. Feel free to reopen, if you encounter this trouble in the future.
