### ISSUE TITLE
How to pass changed slider values inside CropperPreview ?

### ISSUE THREAD

**Issue by Djibdjib** [advanced-cropper/react-advanced-cropper#15]
Hi,
Thx for this unbelivable library !

I made the ImageEditor tutorial and all is great, except that values changed inside are not passed to CropperPreview.

Any helps ?

Thx a lot

**Comment by Norserium** [comment]
@Djibdjib, hello! Do you have a separate preview for the cropped result like [this](https://advanced-cropper.github.io/react-advanced-cropper/docs/guides/recipes#preview-the-result) (preview the result)?

**Comment by Norserium** [comment]
Also it would be helpful, if you create the sandbox, that illustrates your issue. You can use [mine](https://codesandbox.io/s/react-advanced-cropper-image-editor-90gs8z?file=/src/index.tsx) as the reference.

**Comment by Norserium** [comment]
@Djibdjib, do you have the fixed aspect ratio in your project?

**Comment by Djibdjib** [comment]
@Norserium yes i have fixed aspect ratio, (16/9) but there is no fixed aspect ratio in my sandbox.

**Comment by Norserium** [comment]
@Djibdjib, try [this](https://codesandbox.io/s/react-advanced-cropper-image-editor-improved-8jgk8p). 

It works, but I suppose, I should improve `CropperPreview` to make it more flexible like the `Cropper` component.

The anticipated improvements:
1. Add the possibility to pass `backgroundComponent` and `backgroundProps`.
2. Add the loading / unloading image like in `Cropper`. But it should be synchronized with the cropper, so it's need kind of helper `cropper.getStatus()`

But it will be later.

**Comment by Djibdjib** [comment]
@Norserium ,
i do not have the same result as CropperPreview. CropperPreview is perfect for cropped canvas, EditorPreview is perfect for adjustments. I'm trying to merge that...

Perfectly, add adjustments props to CropperPreview, isn't it ?

Regards

**Comment by Norserium** [comment]
> i do not have the same result as CropperPreview

@Djibdjib, could you illustrate this?

**Comment by Djibdjib** [comment]
@Norserium ,

I think that getPreviewStyle() returns to me:

![image](https://user-images.githubusercontent.com/2052365/198386184-60c4ed5c-593c-467d-8ce1-dac7020be0d1.png)

translate3d bug !

**Comment by Norserium** [comment]
@Djibdjib, I can't reproduce it.

![image](https://user-images.githubusercontent.com/9862719/198386850-e931b965-84e0-4ee1-8de9-72cc7cb9e903.png)

However, if you can wait until tomorrow, it can become not actual probable.

**Comment by Djibdjib** [comment]
@Norserium yeah ! i'll continue investigations and maybe surprise tomorrow !

You are great ! reactive and great !

Thx a lot !

**Comment by Djibdjib** [comment]
@Norserium It works now !!

i had to fix the width of the zone preview (to calculate good coefficient), as your example.

Not perfect for the moment because i have to now change this on window resize. It's a detail !

Thx thx thx !!!

**Comment by Norserium** [comment]
@Djibdjib, I rewrote the cropper preview component, so it become easier to got the desired result. Look at [the rewritten example](https://codesandbox.io/s/react-advanced-cropper-image-editor-90gs8z?file=/src/index.tsx). Also this component supports media requests, so it should facilitate your task.

**Comment by Norserium** [comment]
Notice, that the way of using `CropperPreview` was completely changed. It becomes a lot simpler.

**Comment by Djibdjib** [comment]
@Norserium Hi and thx ! update is available on 0.15.0 of npm ?

**Comment by Norserium** [comment]
@Djibdjib, it's available in `0.16.1`. I will assign `latest` tag later.

**Comment by Djibdjib** [comment]
@Norserium export 'CropperPreviewRef' (imported as 'CropperPreviewRef') was not found in 'react-advanced-cropper' on 0.16.0 version...

**Comment by Norserium** [comment]
@Djibdjib, it's strange because there is no such issue in [the codesandbox](https://codesandbox.io/s/react-advanced-cropper-image-editor-90gs8z?file=/src/index.tsx). Are you sure, that you have updated the `react-advanced-cropper`?

**Comment by Djibdjib** [comment]
@Norserium New implementation is perfect, more simple as before ! Nice job !

However, when i resize my window, after preview generated, preview disappear !

![react-cropper](https://user-images.githubusercontent.com/2052365/198999674-33a31587-4165-43f6-8784-d41ed2201b82.gif)

**Comment by Norserium** [comment]
@Djibdjib, well, that's a disadvantage of the new approach. The cropper is destroyed, so the `cropperRef.current` is `null`, and the preview component can't access the data.

But you still can use the previous approach:
```tsx
<CropperPreview
   image={image}
   state={state}
/>
```

**Comment by Djibdjib** [comment]
@Norserium Everything is perfect now ! you are great !!!

Thx a lot for your incredible library, for your reactivity !

**Comment by Norserium** [comment]
@Djibdjib, you are welcome!

**Comment by Norserium** [comment]
>  I will assign latest tag later.

@Djibdjib, feel free to update to `0.17.0`. It's the latest version now.

**Comment by Djibdjib** [comment]
@Norserium thx a lot ! i will update to this !

**Comment by Norserium** [comment]
@Djibdjib, don't forget to retest a little. There should not be any breaking changes that affects you, but better safe than sorry.
