### ISSUE TITLE
Minimal required package

### ISSUE THREAD

**Issue by kla-ko** [advanced-cropper/react-advanced-cropper#16]
Hi
I very much like the react advanced cropper. Got it working quickly.
I'm struggling with the required packaging. I used ``npm install`` to fetch everything. Then I found out by trial and error which packages are required to put onto my web server. From the ``node_modules`` folder, I've used ``react-advanced-cropper/dist`` and also the folders ``classnames`` and ``tslib``. This works, but probably not all files are really required to get cropper running.
Is there a packaging which bundles all resources which are minimally required?

Thanks

**Comment by Norserium** [comment]
@kla-ko, hello! 

It's strange that you need to put the dependencies on your web server by yourself. In any case, there are three dependencies: [advanced-cropper](https://www.npmjs.com/package/advanced-cropper), [classnames](https://www.npmjs.com/package/classnames), [tslib](https://www.npmjs.com/package/tslib).

I assume that you missing `advanced-cropper`.

**Comment by Norserium** [comment]
@kla-ko, any news?

**Comment by Norserium** [comment]
>  I found a dist folder below react-advanced-cropper and I was hoping to find in there all I need. 

No you won't. The dependencies will be in `node_modules`.

Try to execute `npm install react-advanced-cropper` in an empty folder, and then open `node_modules`.

**Comment by kla-ko** [comment]
Alright. Thanks
