### ISSUE TITLE
Getting the cropped image result as a circle when using CircleStencil

### ISSUE THREAD

**Issue by gelform** [advanced-cropper/react-advanced-cropper#18]
I am using the `CircleStencil` with the cropper.

I am successfully getting the canvas and calling `toBlob` to upload the result:
```
const canvas = cropperRef.current?.getCanvas();

if (canvas) {
	const formData = new FormData();
	canvas.toBlob((blob) => {
		if (blob) {
			formData.append('file', blob, Date.now() + '.jpg');
			// formData uploaded successfully
```

However, the image uploaded is a square, not a circle. 

Is there a way to get the circle-cropped image from the canvas?

**Comment by Norserium** [comment]
@gelform, take a look at [this issue](https://github.com/advanced-cropper/react-advanced-cropper/issues/9).

**Comment by gelform** [comment]
Thank you so much! Sorry for the duplicate issue.

**Comment by Norserium** [comment]
@gelform, it's okay. You are welcome!
