### ISSUE TITLE
RN version ?

### ISSUE THREAD

**Issue by hamdij0maa** [advanced-cropper/react-advanced-cropper#19]

**Comment by Norserium** [comment]
@hamdij0maa, I assume, it's possible to create the React Native cropper implementation based on the same `advanced-cropper` core, but still there are a ton of peculiarities. And more important that I don't work with React Native, so I'm not sure that this will be implemented in the near future. 

By the way, what's the situation with croppers for React Native? Could you name the solid libraries?

**Comment by hamdij0maa** [comment]
we tried many, but all available libs are not maintained and with many problems,  [expo-image-cropper example ](https://github.com/thomas-coldwell/expo-image-editor)

**Comment by Norserium** [comment]
@hamdij0maa, that's sadly. 

Currently I don't have plans to port this cropper to React Native. But there is the hope that the community will try to do something, when this library will become more famous.
