### ISSUE TITLE
How to set rectangular stencil to unchangeable image aspect ratio

### ISSUE THREAD

**Issue by kla-ko** [advanced-cropper/react-advanced-cropper#21]
Hi
I'm looking for a way to set the stencil aspect ratio to the same value as the loaded image aspect ratio and at the same time prohibit to change this aspect ratio. I think the stencil initially appears with the image aspect ratio, but then a user can change this ratio.
Note, a user should still be able to change the stencil area.

Any ideas?
Thanks

**Comment by Norserium** [comment]
@kla-ko, hello, nice to meet to you! 

It's the interesting task that can demonstrate the pure flexibility of this cropper. Try to upload the different images in [this sandbox](https://codesandbox.io/s/react-advanced-cropper-aspect-ratio-4xowpz?file=/src/index.tsx).

**Comment by kla-ko** [comment]
Thanks!
``aspectRatio={aspectRatio}`` with ``useState`` is doing the job.

Great product! Please go on completing the docs whenever possible.
Regards,

**Comment by Norserium** [comment]
@kla-ko, you are welcome! 

> Please go on completing the docs whenever possible.

It's so time consuming, especially in the situation when the API is not fully stable.

**Comment by kla-ko** [comment]
Hi @Norserium ,
Interestingly, using your approach to use the aspectRatio function ``const aspectRatio = (state) => { ... }`` also works for ``stencilComponent={CircleStencil}``. So, "Circle" isn't necessarily a "Circle", but an "Oval" where you can even change the aspect ratio dynamically.
![image](https://user-images.githubusercontent.com/69795385/213208598-a41b348b-48c7-4c79-9526-0eb33c9d1c19.png)

Regards

**Comment by kla-ko** [comment]
Just wanted to mention this,  because this might be useful for others ...

**Comment by Norserium** [comment]
@kla-ko, that's important mention. Thank you! I just want to explain the logic stands behind this decision.
