### ISSUE TITLE
How to add two crop boxes on an image and how to get their preview for each

### ISSUE THREAD

**Issue by JuGit-pk** [advanced-cropper/react-advanced-cropper#23]
I want to add two selections on an image, to crop from two different portions of an image and preview them simultaneously.

**Comment by JuGit-pk** [comment]
<img width="503" alt="Screenshot 2023-02-25 at 8 08 29 PM" src="https://user-images.githubusercontent.com/64588251/221364470-adbc13ec-ca7e-4739-a406-5dc6da2782e1.png">

**Comment by JuGit-pk** [comment]
<img width="328" alt="Screenshot 2023-02-25 at 8 12 15 PM" src="https://user-images.githubusercontent.com/64588251/221364614-1f38d6c1-31dd-4454-90f6-4be120e007b7.png">

**Comment by Norserium** [comment]
@JuGit-pk, this cropper doesn't support this feature. It's required a lot of work to implement this alongside with other cropper features.
