### ISSUE TITLE
Pass data to wrapperComponent

### ISSUE THREAD

**Issue by pchr-srf** [advanced-cropper/react-advanced-cropper#24]
Hi @Norserium!

In the [absolute-zoom Tutorial](https://advanced-cropper.github.io/react-advanced-cropper/docs/tutorials/absolute-zoom) you explain how to make a custom wrapperComponent which can include a zoom slider.

Now I'd like to have a zoom slider and some buttons to change the ratio of the stencil (which is not difficult). But if the cropper is wrapped in a wrapperComponent which contains the slider, I would also like to put the buttons in the same place. Ideally I would also be able to define the available ratios from the parent component, but I don't know how.

So my question is: How can I pass data to the wrapperComponent?

**Comment by Norserium** [comment]
@pchr-srf, if I understand you correctly, you need to use `wrapperProps` property to pass the props to the wrapper component.
```jsx
<Cropper
   wrapperProps={{ property: 1 }}
/>
```

**Comment by pchr-srf** [comment]
Hah, perfect! That works well, thank you for the quick reply!

**Comment by Norserium** [comment]
@pchr-srf, you are welcome!

**Comment by pchr-srf** [comment]
Ah, another question, sorry... how can I change stencilProps from inside a custom wrapper?

Sandbox: https://codesandbox.io/s/festive-hill-6mn37x?file=/src/wrapper.tsx
<img width="602" alt="image" src="https://user-images.githubusercontent.com/21658108/222706054-24530205-b93b-4a7e-8a3e-0f40bd75b5ca.png">


(and since I'm already asking questions, is there a small example on how to use a [CropperBackgroundImage](https://advanced-cropper.github.io/react-advanced-cropper/docs/components/CropperBackgroundImage)?

Here's my goal:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/21658108/222706977-479a0c31-4957-4adf-9b04-b7c3343f033f.png">
(Zoomslider + rotation is working from inside the custom wrapper 😄)

**Comment by pchr-srf** [comment]
Handled it right now by keeping the state in the parent and passing a callback to the custom Wrapper, works for now 😄  If you have a better idea, i'd be happy to hear it
<img width="594" alt="image" src="https://user-images.githubusercontent.com/21658108/222746186-23f32bd7-4487-486d-b28c-adf5ea291ef4.png">

**Comment by Norserium** [comment]
@pchr-srf, it's actually the most straightforward and clean solution. You will do the same thing if your buttons were outside the cropper.
