### ISSUE TITLE
The image ratio changes while using Cropper Rotation

### ISSUE THREAD

**Issue by CalvinJamesHeath** [advanced-cropper/react-advanced-cropper#25]
The image ratio changes while using Cropper Rotation, and it doesn't return to the default position after switching back to the vertical aligment.
The mobile cropper, which allows you to rotate the image without affecting the crop ratio, is exactly how I would like the default behavior to operate. Is it possible to crop an image using the imageEditor component while maintaining auto resize enabled, just like with the mobile cropper? I appreciate you reading and for this fantastic cropper. Thank you! 

https://user-images.githubusercontent.com/72168052/224753224-bb54fd99-4e36-4045-88f6-87a3dcb41e3c.mov

**Comment by Norserium** [comment]
@CalvinJamesHeath, sorry for such a long answer delay. The algorithms can be easily customized. If you just want to preserve the aspect ratio, there is [the solution](https://codesandbox.io/s/react-advanced-cropper-rotate-otyjqx?file=/src/algorithms.tsx).

**Comment by Norserium** [comment]
@CalvinJamesHeath, but I assume that you want to get [this behavior](https://codesandbox.io/s/react-advanced-cropper-rotate-with-basis-4eymkn?file=/src/algorithms.tsx), i.e. cropper should return the stencil size to its previous size before rotation.

**Comment by CalvinJamesHeath** [comment]
@Norserium thank you so much! Works amazing. 🙏🏼👏🏼🏅
