### ISSUE TITLE
Typescript Definitions issues 

### ISSUE THREAD

**Issue by Uniphix** [advanced-cropper/react-advanced-cropper#27]
I am trying to use your library and there are some issues where the typescript definitions are throwing errors.

```
(alias) const CropperFade: FC<Props>
import CropperFade
Type '{ children: Element[]; className: string; visible: boolean; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Props'.ts(2322)
```

Is an example of this error.  

I noticed the typescript definition outputs the results like this...

```
import { CSSProperties, FC } from 'react';
interface Props {
    visible?: unknown;
    className?: string;
    style?: CSSProperties;
}
export declare const CropperFade: FC<Props>;
export {};
```

It feel it is honestly better to use this when trying to support TypeScript etc.  And react future versions...

Example of what I think it should be.
```
import { FC } from 'react';
type Props = {
    visible?: unknown
} & JSX.IntrinsicElements["div"]
export declare const CropperFade: FC<Props>;
export {};
```

To do this you would need to change the file to look like this
```
import React, { CSSProperties, FC } from 'react';
import cn from 'classnames';

type Props = {
	visible?: unknown
} & JSX.IntrinsicElements["div"]

export const CropperFade: FC<Props> = ({ visible, className, style, children }) => {
	return (
		<div
			style={style}
			className={cn(className, 'advanced-cropper-fade', Boolean(visible) && 'advanced-cropper-fade--visible')}
		>
			{children}
		</div>
	);
};
```

**Comment by Norserium** [comment]
@Uniphix, I assume that it's associated with the following breaking changes in React 18:
> The children prop was removed from React.FunctionComponent (React.FC) so you have to declare it explicitly in your component properties.

I've adapted the typing for this changes in `0.19.0`. Check it.

**Comment by Norserium** [comment]
@Uniphix, any news?

**Comment by Norserium** [comment]
@Uniphix, I close this issue, but feel free to reopen in the future.
