### ISSUE TITLE
filters not working on ios phone (safari and chrome)

### ISSUE THREAD

**Issue by ilik666** [advanced-cropper/react-advanced-cropper#28]
brightness: 0,
hue: 0,
saturation: 0,
contrast: 0  
![2023-04-10 00 15 38](https://user-images.githubusercontent.com/28037982/230796862-b1446137-16e8-4578-9845-a3caeaaa1cea.jpg)

**Comment by Norserium** [comment]
@ilik666, alas, Safari doesn't support [canvas.filter](https://caniuse.com/mdn-api_canvasrenderingcontext2d_filter). 

You can use the polyfill, external libraries or write the filters by yourself. I've added the using of polyfill in [the example](https://advanced-cropper.github.io/react-advanced-cropper/docs/tutorials/image-editor), check it.

**Comment by ilik666** [comment]
@Norserium thank you!
