### ISSUE TITLE
Typescript type issue

### ISSUE THREAD

**Issue by Hafiz-Waqar** [advanced-cropper/react-advanced-cropper#31]
<img width="627" alt="Screenshot 2023-05-11 at 2 13 52 PM" src="https://github.com/advanced-cropper/react-advanced-cropper/assets/40634969/168aaf34-d8ad-4852-ab1b-e7600d357487">
I Just upgrade the version to 0.19.2  but getting this issue and not getting any solution for that.

**Comment by Norserium** [comment]
@Hafiz-Waqar, try to update to `0.19.3`.

**Comment by Norserium** [comment]
@Hafiz-Waqar, is this issue still actual?

**Comment by Norserium** [comment]
@Hafiz-Waqar, any news?

**Comment by Norserium** [comment]
@Hafiz-Waqar, I close this issue, but feel free to reopen in the future.
