### ISSUE TITLE
How can i add filters? like black & white. I see you have given Hue, Staturation sliders. But what about proper filters?

### ISSUE THREAD

**Issue by Mubasher-Skylinx** [advanced-cropper/react-advanced-cropper#33]

**Comment by Norserium** [comment]
@Mubasher-Skylinx, what do you mean by "proper filters"? You can do absolutely what you want with canvas.

**Comment by Mubasher-Skylinx** [comment]
https://codesandbox.io/s/fervent-bird-5g26jk?file=/src/components/ImageEditor.jsx

here i have added list in of filters but its not applying

**Comment by Norserium** [comment]
@Mubasher-Skylinx, I don't see any filters in the code.

**Comment by Mubasher-Skylinx** [comment]
![image](https://github.com/advanced-cropper/react-advanced-cropper/assets/116548357/38a14c69-5e06-4bf0-9b72-8651790b4d97)
here

**Comment by Norserium** [comment]
@Mubasher-Skylinx, are you sure that you gave the link to the right codesandbox?

![image](https://github.com/advanced-cropper/react-advanced-cropper/assets/9862719/3c4af9ae-f5c8-40fb-871e-a0562844cd8d)

**Comment by Mubasher-Skylinx** [comment]
I am really sorry
here it is
https://codesandbox.io/s/wonderful-ioana-yj5qnl?file=/src/App.js

**Comment by Norserium** [comment]
@Mubasher-Skylinx, [there you go](https://codesandbox.io/s/react-advanced-cropper-filters-s6tns3). There is [the tutorial ](https://advanced-cropper.github.io/react-advanced-cropper/docs/tutorials/image-editor/#preview) that describe this process.

**Comment by Mubasher-Skylinx** [comment]
Thank you so much <3. It means alot

**Comment by Norserium** [comment]
@Mubasher-Skylinx, you are welcome!
