### ISSUE TITLE
how to rotate image using a slider? from -360 to 360

### ISSUE THREAD

**Issue by Mubasher-Skylinx** [advanced-cropper/react-advanced-cropper#34]

**Comment by Norserium** [comment]
@Mubasher-Skylinx, there is the [react-mobile-cropper](https://github.com/advanced-cropper/react-mobile-cropper) based on this library.

You can look at the source of [the navigation block](https://github.com/advanced-cropper/react-mobile-cropper/blob/master/src/components/Navigation.tsx). It's slightly complicated, but you can take the important parts for you.

If you make the sandbox, I can try to do something.

**Comment by Mubasher-Skylinx** [comment]
https://codesandbox.io/s/flamboyant-fermat-zp538c?file=/src/styles/ImageEditor.css

here is the working example
please can you fix the the zoom functionality. when i zoom beyond to it automatically zoom too much and when i zoom out but not fully using slider it automatically zooms out to full even i haven't reached at left side of slider

and also can you improve my slider code for rotation

**Comment by Norserium** [comment]
@Mubasher-Skylinx, technically, you should do something like [this](https://codesandbox.io/s/fervent-bird-5g26jk?file=/src/components/ImageEditor.jsx). But the current algorithm of absolute zoom calculation may not fit to your requirements.

**Comment by Mubasher-Skylinx** [comment]
This is also good thank you
