### ISSUE TITLE
resize work reverse in rtl app

### ISSUE THREAD

**Issue by soraya-mi** [advanced-cropper/react-advanced-cropper#36]
Hi,

My app is RTL, so I have set the "dir" property of the "html" tag to "rtl". However, I'm facing an issue when trying to resize the cropper area by dragging its corners. The behavior seems to be reversed. When I drag the corners outward, the crop area becomes smaller, and when I drag them inward, it becomes larger.

I attempted to resolve this problem by changing the CSS direction property of the cropper container to "ltr," but it didn't solve the issue. Could you please advise me on what I should do to fix this problem?

**Comment by Norserium** [comment]
@soraya-mi, try to set the custom class for the cropper and add the following rule for it:
```css
direction: ltr;
```

**Comment by soraya-mi** [comment]
i tried that, it didn't work. it only works when i change direction of html

**Comment by soraya-mi** [comment]
the problem was the postcssRTl plugin which affects cropper behavior in rtl direction.

**Comment by Norserium** [comment]
@soraya-mi, all's well that ends well. Thank you for your information, it can be very useful to other users. Good luck!
