### ISSUE TITLE
editor.setState() is working?

### ISSUE THREAD

**Issue by stylessh** [advanced-cropper/react-advanced-cropper#38]
Hello! I want to save the editor state so when I remount it, it saves the previous changes.
But it doesn't seem to work.

editorState is the saved state.
![image](https://github.com/advanced-cropper/react-advanced-cropper/assets/45767683/f0a49cfe-c7c6-4fdf-9d1e-e6844ff9d8c6)
![image](https://github.com/advanced-cropper/react-advanced-cropper/assets/45767683/853d509d-1757-4476-a4bd-03ced429b500)

Here is where I "get" the value store on the useState, but it has the default state anyway.
![image](https://github.com/advanced-cropper/react-advanced-cropper/assets/45767683/9359fb5e-5b08-4b8b-818d-ba17149ead9e)

Any idea on how can I achieve this?

**Comment by Norserium** [comment]
@stylessh, could you reproduce the issue in the codesandbox? There is [my attempt](https://codesandbox.io/s/react-advanced-cropper-c4ynn8?file=/src/index.tsx).

**Comment by stylessh** [comment]
hey @Norserium, thanks a lot for your response. That is what I want to achieve, but instead I want to restore the previous state when the Cropper is mounted again. If you want I can create a codesandbox

**Comment by Norserium** [comment]
@stylessh, I assume, that you trying to set state before the cropper loads an image. 

To facilitate the implementing of the desired result, you can use the fields from the saved state and pass them to `defaultCoordinates`, `defaultVisibleArea` and `defaultTransforms`.

**Comment by Norserium** [comment]
The codesandbox may be useful.

**Comment by stylessh** [comment]
I'll try and let you know

**Comment by stylessh** [comment]
Got it working now man, thanks a lot. Check out the [example here](https://codesandbox.io/s/react-advanced-cropper-forked-mf2kk6?file=/src/index.tsx) so it might help someone in the future.

Now when you save the state, and remount the component, it takes the saved state by default.


https://github.com/advanced-cropper/react-advanced-cropper/assets/45767683/6ebc9574-9271-44db-aa92-a91b307fad13

**Comment by Norserium** [comment]
@stylessh, you are welcome!
