### ISSUE TITLE
Error using in Next JS 

### ISSUE THREAD

**Issue by intaek-h** [advanced-cropper/react-advanced-cropper#4]
I installed react-advanced-cropper in my nextjs 12.2 project and copy pasted the code below
```
import React, { useState, useRef } from "react";
import { CropperRef, Cropper } from "react-advanced-cropper";
import "react-advanced-cropper/dist/style.css";

const Uploader = () => {
  const [image, setImage] = useState(
    "https://images.unsplash.com/photo-1599140849279-1014532882fe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1300&q=80"
  );

  const onChange = (cropper: CropperRef) => {
    console.log(cropper.getCoordinates(), cropper.getCanvas());
  };

  return <Cropper src={image} onChange={onChange} className={"cropper"} />;
};

export default Uploader;
```
I tried to import this `Uploader` component to a next page and this error popped up.

> ./node_modules/advanced-cropper/styles/index.scss
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-advanced-cropper/dist/index.esm-bundler.js

[This is what nextjs doc says about this case](https://nextjs.org/docs/messages/css-npm)

Please check and let me know!

**Comment by Norserium** [comment]
@intaek-h, hello! I've found the source of this bug. I'm working at it.

**Comment by Norserium** [comment]
@intaek-h, try to update to `0.10.4`.

**Comment by ordinaryprobably** [comment]
@Norserium good to hear that! May I ask when the fix will be applied? I really am fascinated by your work and want to use it in my project asap!

**Comment by Norserium** [comment]
@ordinaryprobably, the fix should be published now in `0.10.4`.

**Comment by intaek-h** [comment]
@Norserium I checked 0.10.4 and it works well. Thanks for instant update and keep up the good work!

**Comment by Norserium** [comment]
@intaek-h, you are welcome!
