### ISSUE TITLE
Replacing CustomBackgroundWrapper with a custom component results in component not working

### ISSUE THREAD

**Issue by tutmryan** [advanced-cropper/react-advanced-cropper#42]
**Description**:
When replace the backgroundWrapperComponent provided in FixedCropper, the FixedCropper component doesn't work anymore and renders a white canvas.

Expected Behavior:
Replacing the backgroundWrapperComponent in FixedCropper should maintain the functionalities of the library.

Actual Behavior:
The component renders a white empty canvas

Steps to Reproduce:
1. Create a custom background wrapper component
![image](https://github.com/advanced-cropper/react-advanced-cropper/assets/96557904/7cfc55f5-d70d-4ca8-a4b4-c48fc4501b19)
2. Pass it as props to backgroundWrapperComponent in FixedCropper
![image](https://github.com/advanced-cropper/react-advanced-cropper/assets/96557904/2c6ade75-6806-40d1-b287-d472d60416d1)
3. The result:
![image](https://github.com/advanced-cropper/react-advanced-cropper/assets/96557904/890d89b5-3193-430a-80b1-7581ec8488f2)

**Comment by Norserium** [comment]
@tutmryan, cropper doesn't pass `image` prop to the `backgroundWrapperComponent`: https://github.com/advanced-cropper/react-advanced-cropper/blob/8aca4a536ab3be2291db441eb3acabc84109d40d/src/components/AbstractCropper.tsx#L172-L176

Where did you find that example?

**Comment by tutmryan** [comment]
Right, I was overriding the image prop that is being used by the BackgroundWrapper you meant? Thank you for clearing that up!

Closing this issue.
