### ISSUE TITLE
Preview to Canvas?

### ISSUE THREAD

**Issue by caprica** [advanced-cropper/react-advanced-cropper#45]
Is it possible/feasible to have the dynamic cropper preview image render directly to an HTML Canvas component?

What I have working at the moment is the normal preview to a React component, then on a button press I grab the image and render into an off-screen canvas. It would be very nice instead to be able to render the preview directly into a pre-prepared canvas. I would use this to render the preview image into some scene, and then paint various gradients or whatever over it. But this lacks the "live" update of the preview as it changes.

**Comment by Norserium** [comment]
@caprica, did you see [this example](https://advanced-cropper.github.io/react-advanced-cropper/docs/tutorials/image-editor/#preview)?

**Comment by caprica** [comment]
I did originally see that example, but I guess didn't look deeply enough to spot that it was rendering the preview to a canvas.

If I understand correctly, instead of using something like the AdjustableImage to set hue, saturation, brightness like the example does, I can render whatever I want there, it's just a normal canvas at the heart of it.

Presumably the canvas size can be bigger than the preview image,.

Anyway, thanks a lot for the pointer, I'll see if I can make this work how I need it to.

**Comment by Norserium** [comment]
> If I understand correctly, instead of using something like the AdjustableImage to set hue, saturation, brightness like the example does, I can render whatever I want there, it's just a normal canvas at the heart of it.

@caprica, exactly. `AdjustableImage` is the custom component that build around a normal canvas.
```tsx
import React, { forwardRef, useRef, CSSProperties, useLayoutEffect } from 'react';
import cn from 'classnames';
import { mergeRefs } from 'react-advanced-cropper';
import './AdjustableImage.scss';

interface Props {
    src?: string;
    className?: string;
    crossOrigin?: 'anonymous' | 'use-credentials' | boolean;
    brightness?: number;
    saturation?: number;
    hue?: number;
    contrast?: number;
    style?: CSSProperties;
}

export const AdjustableImage = forwardRef<HTMLCanvasElement, Props>(
    ({ src, className, crossOrigin, brightness = 0, saturation = 0, hue = 0, contrast = 0, style }: Props, ref) => {
        const imageRef = useRef<HTMLImageElement>(null);
        const canvasRef = useRef<HTMLCanvasElement>(null);

        const drawImage = () => {
            const image = imageRef.current;
            const canvas = canvasRef.current;
            if (canvas && image && image.complete) {
                const ctx = canvas.getContext('2d');
                canvas.width = image.naturalWidth;
                canvas.height = image.naturalHeight;

                if (ctx) {
                    ctx.filter = [
                        `brightness(${100 + brightness * 100}%)`,
                        `contrast(${100 + contrast * 100}%)`,
                        `saturate(${100 + saturation * 100}%)`,
                        `hue-rotate(${hue * 360}deg)`,
                    ].join(' ');

                    ctx.drawImage(image, 0, 0, image.naturalWidth, image.naturalHeight);
                }
            }
        };

        useLayoutEffect(() => {
            drawImage();
        }, [src, brightness, saturation, hue, contrast]);

        return (
            <>
                <canvas
                    key={`${src}-canvas`}
                    ref={mergeRefs([ref, canvasRef])}
                    className={cn('adjustable-image-element', className)}
                    style={style}
                />
                {src ? (
                    <img
                        key={`${src}-img`}
                        ref={imageRef}
                        className={'adjustable-image-source'}
                        src={src}
                        crossOrigin={crossOrigin === true ? 'anonymous' : crossOrigin || undefined}
                        onLoad={drawImage}
                    />
                ) : null}
            </>
        );
    },
);

AdjustableImage.displayName = 'AdjustableImage';
```

**Comment by Norserium** [comment]
@caprica, I close this issue, but feel free to reopen in the future.
