### ISSUE TITLE
Blinking issue with the image on page loads.

### ISSUE THREAD

**Issue by TahaKhanAbdalli** [advanced-cropper/react-advanced-cropper#47]
I have incorporated the **CropperFade** component to facilitate image display within our application. However, I am experiencing a persistent flickering or blinking effect under specific circumstances. This effect occurs when navigating between pages and returning to our application tab. Notably, the blinking effect, reminiscent of the initial image load, is observed both during the initial loading process and upon switching back to our application tab from another browser tab.

**Potential Cause:**
After careful examination, it seems that the recurring issue may be related to the re-rendering behavior triggered by the **visible** prop of the **CropperFade** component.

**Request for Assistance:**
I am reaching out to seek your guidance on addressing this concern. If you could provide insights or suggest potential solutions to mitigate the flickering effect associated with the CropperFade component's visible prop, it would greatly assist in enhancing the user experience within our application.

Thank you for your time and attention to this matter. I look forward to your valuable insights and recommendations.

_Note: The Issue is only occurring on Safari Browser._

**Comment by Norserium** [comment]
@TahaKhanAbdalli, could you create the codesandbox that reproduces this issue?

**Comment by TahaKhanAbdalli** [comment]
Closing the issue as we have internally fixed it.

Thanks @Norserium
