### ISSUE TITLE
Mouse resizing doesn't work

### ISSUE THREAD

**Issue by mohammadius** [advanced-cropper/react-advanced-cropper#50]
Hi, I'm trying to use react-advanced-cropper in my web application but my problem is that resizing the crop box with mouse doesn't work. resizing, moving and zooming does work with touch input and also zooming works with mouse scroll wheel. i've tested it with version 0.19.4 and 0.19.3. i'm giving the Cropper a base64 image and that's it.no onChange listeners or ref or states.

**Comment by Norserium** [comment]
@mohammadius, could you provide the codesandbox that reproduces this issue? Do you encounter this trouble in the documentation examples?

**Comment by mohammadius** [comment]
well, that's the problem, I can't reproduce the problem in CodeSandBox. i have tried to do it in [here](https://codesandbox.io/p/sandbox/sharp-brook-dclx46?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpz45hs100073j6gkyphf4y7%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpz45hs100033j6gwio9mlm5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpz45hs100043j6g17s610j1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpz45hs100063j6gzfj6vm86%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B44.21304757690606%252C55.78695242309394%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpz45hs100033j6gwio9mlm5%2522%253A%257B%2522id%2522%253A%2522clpz45hs100033j6gwio9mlm5%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpz45hs100063j6gzfj6vm86%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpz45hs100053j6gsyxqroe5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpz45hs100063j6gzfj6vm86%2522%252C%2522activeTabId%2522%253A%2522clpz45hs100053j6gsyxqroe5%2522%257D%252C%2522clpz45hs100043j6g17s610j1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpz45hs100043j6g17s610j1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), it's basically what i have in my own project. i have the cropper inside a popup and i'm rendering that with [createPortal](https://react.dev/reference/react-dom/createPortal), could that cause a problem? and i have to use createPortal, for now at least.

**Comment by Norserium** [comment]
@mohammadius, could you reproduce in the codesandbox the using of `createPortal`?

**Comment by mohammadius** [comment]
okay, so the problem was kind of a miscommunication issue with my team. the problem was that there was another component rendering in the background that had mouse event listeners on document, and in those event listeners they had called [preventDefault](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) and [stopPropagation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) on the event and one or both of them (probably stopPropagation) caused the cropper handles to not get the mouse events. calling any of those methods in those listeners were unnecessary anyways, so removing them fixed the problem.
