### ISSUE TITLE
change the stencilComponent to use an oval instead of a circle or rectangle? 

### ISSUE THREAD

**Issue by CalvinJamesHeath** [advanced-cropper/react-advanced-cropper#51]
I tried changing the css, the coordenates, and sizes of the Cropper but I couldnt get the desired result. Thank you.

**Comment by CalvinJamesHeath** [comment]
stencilProps={{
						grid: true,
						movable: cropperEnabled,
						resizable: cropperEnabled,
						lines: cropperEnabled,
						handlers: cropperEnabled,
						rotatable: cropperEnabled,
						overlayClassName: cn(
							'image-editor__cropper-overlay',
							!cropperEnabled && 'image-editor__cropper-overlay--faded',
						),
					}}

**Comment by CalvinJamesHeath** [comment]
So at [](https://advanced-cropper.github.io/react-advanced-cropper/docs/guides/#passing-props-to-the-stencil) it says : To customize the default stencils you should pass props to stencilProps props as object (read [here](https://advanced-cropper.github.io/react-advanced-cropper/docs/guides/#passing-props-to-the-stencil) in detail). However the link is broken.

**Comment by Norserium** [comment]
@CalvinJamesHeath, do you want to get [the following result](https://codesandbox.io/p/sandbox/react-advanced-cropper-oval-l37hrf)?

**Comment by CalvinJamesHeath** [comment]
I'm attempting to accomplish the following with the CircleStencil or any other tool you deem appropriate. 
What I want to achieve:
<img width="358" alt="Screenshot 2024-01-20 at 11 09 06 PM" src="https://github.com/advanced-cropper/react-advanced-cropper/assets/72168052/cd5b5fe2-5943-4ec3-8713-59e03dccbec3">

What I get with the default configuration:
<img width="358" alt="Screenshot 2024-01-20 at 11 08 54 PM" src="https://github.com/advanced-cropper/react-advanced-cropper/assets/72168052/58b7b238-443f-4234-abd3-8ddda50e1130">


Also with the desired oval cropped image, I also want to show the image preview besides the cropper. 

Thank you @Norserium

**Comment by CalvinJamesHeath** [comment]
And the desired cropper should not strech all the way to the circle stencil, but only to the width of the oval stencil

**Comment by CalvinJamesHeath** [comment]
`// // ellipse / oval css
.advanced-cropper-circle-stencil__draggable-area,
.advanced-cropper-circle-stencil__overlay,
.advanced-cropper-circle-stencil__preview,
.advanced-cropper-circle-stencil__grid {
	position: relative;
	height: 100%;
	width: 90% !important;
}; What I targeted for the example`

**Comment by Norserium** [comment]
@CalvinJamesHeath, I don't get you. The circle stencil limits aspect ratio to `1/1`, so you should create your own stencil or customize the rectangle stencil.

**Comment by CalvinJamesHeath** [comment]
Well then I guess my question is how to do that, can you pass a default aspect ratio that can expand or shrink but always look like an oval. I opened before another issue before because the "Create your own Custom Stencil section link" was invalid. 

Thanks again.

**Comment by CalvinJamesHeath** [comment]
So I added stencilProps={{aspectRatio: 4 / 5, }} for an ellipse/oval aspect.
How do I get back the preview lines or oval shape inside the handler? Because the previewClassName only shows if Im using the CircleStencil.
<img width="358" alt="Screenshot 2024-01-21 at 12 05 49 PM" src="https://github.com/advanced-cropper/react-advanced-cropper/assets/72168052/2e43d30e-bd0c-4a0e-b2c2-6fa509de733a">

**Comment by CalvinJamesHeath** [comment]
The preview className works perfectly, I used:
`.preview {
	border: dashed 2px rgba(255, 255, 255, 0.764);
	border-radius: 50%;
}`

Thank you.

**Comment by Norserium** [comment]
@CalvinJamesHeath, you are welcome!

**Comment by CalvinJamesHeath** [comment]
I have a question about image cropping. When I load an image into the cropper, it has its unique width and height. However, when I save the cropped image and resize it to be 600x600 in the backend, the resulting image dimensions differ from the initial cropped dimensions.

Is there a way to set a predetermined width and height for any image added to ensure consistency in the final cropped image?

**Comment by Norserium** [comment]
@CalvinJamesHeath, if you use the canvas to get the cropped image, you can use native approach:
```
const canvas = cropper.getCanvas({
        height: 600,
        width: 600,
})
```
