### ISSUE TITLE
How to set the maximum zoom?

### ISSUE THREAD

**Issue by Eriickson** [advanced-cropper/react-advanced-cropper#52]
I have been using this library and I have loved it, the documentation is a bit extensive and I am still in the process of reading it completely, therefore I have a question and that is how could I apply a maximum zoom to my images? because currently the user could do some kind of infinite zoom and I would like to restrict this feature to the users of my application

**Comment by Norserium** [comment]
@Eriickson, well, you can set `minWidth` and `minHeight`.

It's half-measure, but it will prevent infinite zoom, otherwise you can customize the `transformImageAlgorithm` to limit zoom explicitly.

**Comment by Norserium** [comment]
@Eriickson, I close this issue, but feel free to reopen in the future.
