### ISSUE TITLE
How to implement undo redo functionality while editing image?

### ISSUE THREAD

**Issue by Abhi-Radadiya** [advanced-cropper/react-advanced-cropper#54]
I am developing platform where user need to upload image and edit which has simple functionality rotate, crop and flip. 

Now I have implemented undo-redo functionality for rotation and flipping an image but how to deal with crop?

https://github.com/advanced-cropper/react-advanced-cropper/assets/140842297/2cf3e838-3ca2-49a3-81af-9ac8890b7fb3

**Comment by Norserium** [comment]
@Abhi-Radadiya, you can remember the state on its change (`onChange` callback) and then set the corresponding state by `setState` method.

**Comment by Norserium** [comment]
@Abhi-Radadiya, I close this issue, but feel free to reopen in the future.
