### ISSUE TITLE
Cropper for multiple images

### ISSUE THREAD

**Issue by ssatriya** [advanced-cropper/react-advanced-cropper#60]
I am using the cropper for multiple images, currently only change the src in Cropper component like src={files[current]}

it does work but I can't download all images with only one click, I need to loop to all images in frontend also. My goal is to download all images without looping it in frontend.

I came with an idea of creating ref dynamically, but when I create 2 refs (as example 2) the other refs become null. Like when I displaying first image, second refs become null and the other way around. I was thinking to just loop between all those refs to download it all in one button click. Any idea on how to achieve that?

I use this to generate refs

`const imageRef = files.map(() => React.createRef<FixedCropperRef>());`

Here's also some screenshot when only one of them has value

![Screenshot_35](https://github.com/advanced-cropper/react-advanced-cropper/assets/62689382/c2fffa29-076f-470e-8c73-3d3e6481b909)

![Screenshot_36](https://github.com/advanced-cropper/react-advanced-cropper/assets/62689382/613edbfb-69d9-440f-8c2d-cc33bb209d2f)

**Comment by Norserium** [comment]
@ssatriya, you can save an image to a special array before you change `src`. But I'm not sure that I get what you want to achieve.

**Comment by ssatriya** [comment]
@Norserium Yap, I already find the solution. In my case just using carousel and dynamically create Ref for each image. With this i think it also easier to perform image editing (like change brightness). Don't know about performance but it works. 

Other questions maybe, is it normal to get bigger size after cropping? I tried to 1  mb image and get like 5-6 mb in result after cropped.

**Comment by Norserium** [comment]
@ssatriya, yes, it's, because it depends on the format that you use when you get a content from `canvas`:  [toDataURL](https://developer.mozilla.org/ru/docs/Web/API/HTMLCanvasElement/toDataURL), [toBlob](https://developer.mozilla.org/ru/docs/Web/API/HTMLCanvasElement/toBlob).

For example:
```
canvas.toDataURL("image/jpeg");
```

By default, that methods uses `image/png` and this format doesn't use lossy compression and it often has larger weight.

**Comment by ssatriya** [comment]
Just want to let anyone know in case of having this issue, i create .jpeg and it give me fairly small size after crop. 

Thanks

**Comment by Norserium** [comment]
@ssatriya, you are welcome!
