### ISSUE TITLE
Breaking change in 0.19.5 from 0.19.4 (a patch version!)

### ISSUE THREAD

**Issue by ariesclark** [advanced-cropper/react-advanced-cropper#62]
``CropperRef`` is not returning the cropped canvas at all, and it simply returns the original version. This includes via: ``getCanvas`` and ``getImage``. I was definitely not expecting breakage, and I didn't even notice until I walked back through the changes I made.

I had to **revert the version** to ``0.19.4`` as I was not able to get the expected output image.

**Comment by Norserium** [comment]
@ariesclark, it's not the breaking change, it was the accidental bug. I'm sorry for that. It's fixed now in `0.19.6`.

**Comment by Norserium** [comment]
@ariesclark, `0.19.5` marked as deprecated.
