### ISSUE TITLE
Batch images

### ISSUE THREAD

**Issue by mrdotb** [advanced-cropper/react-advanced-cropper#65]
Hello,

:+1:  Thank you for this great library !

I have a use case which involve multiples pictures and  I want your opinion.
The flow I want is the following:
- The user define a preset by using the cropper component on the first picture (rotate, crop...)
- The preset is applied to many pictures

What is the best way to achieve this ?

**Comment by mrdotb** [comment]
I manage to make it work using function from `advanced-cropper/canvas` directly.
The source code is easy to  read :+1:

**Comment by Norserium** [comment]
@mrdotb, all's well that ends well. I assume that you've used `drawCropperArea` function. It's the suitable approach.
