### ISSUE TITLE
CORS errors while passing the src into Cropper Component

### ISSUE THREAD

**Issue by l1lgadil1** [advanced-cropper/react-advanced-cropper#68]
I'm gettings CORS errors in network, and console. I've implemented Image editor as it is showed in Documentation. At the same time, backend's Access-Control-Allow-Origin set as "*". Any help is appreciated 
<img width="832" alt="Снимок экрана 2024-06-12 в 18 38 56" src="https://github.com/advanced-cropper/react-advanced-cropper/assets/92325418/e9b44109-40ef-483d-8e9b-fcb902cc1010">
![telegram-cloud-photo-size-2-5411457625738041413-y](https://github.com/advanced-cropper/react-advanced-cropper/assets/92325418/e421cd4f-e48d-4d42-bf9a-2c4215ed5d5d)
<img width="973" alt="image" src="https://github.com/advanced-cropper/react-advanced-cropper/assets/92325418/2c3f9879-f8d4-4a3a-abf2-7b835b4bbfb9">

**Comment by Norserium** [comment]
@l1lgadil1, you should check the server response.

I don't see `Access-Control-Allow-Origin` header:
![image](https://github.com/advanced-cropper/react-advanced-cropper/assets/9862719/999e0b91-6182-4504-be5a-a25594c05996)
