### ISSUE TITLE
How to disable Zoom on mousewheel?

### ISSUE THREAD

**Issue by auditt98** [advanced-cropper/react-advanced-cropper#8]
I'd like to turn off mouse wheel scrolling to zoom. Is there a way to disable that behaviour?

**Comment by Norserium** [comment]
@auditt98, but preserve touch zoom? If you want to disable all kinds of zoom use [this advice](https://github.com/advanced-cropper/react-advanced-cropper/issues/6#issuecomment-1234505557).
