### ISSUE TITLE
How to get cropped area (only inside the stencils)?

### ISSUE THREAD

**Issue by auditt98** [advanced-cropper/react-advanced-cropper#9]
I'm trying to crop an image and my stencilComponent is currently set to circle. I'd like the final cropped image to be circular (the part inside of the stencil area). How would I be able to achieve that?
![image](https://user-images.githubusercontent.com/41824920/191469042-05aec228-fad8-4f7d-ad55-04b6ee714535.png)

**Comment by Norserium** [comment]
Hello, @auditt98!

The stencil defines the rectangle area that will be cropped, and that's all. It's the common behavior for all cropper that I know. However, you can  process the canvas to get the needed result.

[The example for you](https://codesandbox.io/s/react-advanced-cropper-circle-27yr36?file=/src/index.tsx).

**Comment by auditt98** [comment]
Thank you so much for the help! @Norserium
